services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/webpage
    container_name: frontend_container
    ports:
      - "3000:80"

